/**
 * Transcript fetcher for Adjuster University lessons.
 * For each lesson with a Vimeo video:
 *   1. Opens the lesson page in Playwright to get the authenticated Vimeo embed URL
 *   2. Downloads audio-only using yt-dlp (with session cookies)
 *   3. Uploads audio to Gemini Files API
 *   4. Asks Gemini to transcribe
 *   5. Patches the existing lesson .md file to insert the transcript
 *
 * Run from Mac Terminal:
 *   node /Users/hakielmcqueen/mcp-automation/scripts/transcribe-lessons.mjs
 *
 * Options:
 *   --course field-property     Only transcribe one course (use slug from index.json)
 *   --max N                     Stop after N transcriptions (for testing)
 *   --lesson lesson-slug        Transcribe a single specific lesson
 */
import { chromium } from "playwright";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { GoogleAIFileManager } from "@google/generative-ai/server";
import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import dotenv from "dotenv";
dotenv.config({ path: "/Users/hakielmcqueen/mcp-automation/.env" });

const SESSION_PATH = "/Users/hakielmcqueen/mcp-automation/adjuster_university_session.json";
const OUTPUT_DIR = path.join(process.env.HOME, "Desktop/adjuster-university-content");
const INDEX_PATH = path.join(OUTPUT_DIR, "index.json");
const AUDIO_TMP = path.join(process.env.HOME, "Desktop/adjuster-university-content/tmp-audio");

const FILTER_COURSE = process.argv.includes("--course")
  ? process.argv[process.argv.indexOf("--course") + 1] : null;
const FILTER_LESSON = process.argv.includes("--lesson")
  ? process.argv[process.argv.indexOf("--lesson") + 1] : null;
const MAX = process.argv.includes("--max")
  ? parseInt(process.argv[process.argv.indexOf("--max") + 1]) : Infinity;

if (!fs.existsSync(INDEX_PATH)) {
  console.error("index.json not found. Run scrape-adjuster-university.mjs first.");
  process.exit(1);
}
if (!process.env.GOOGLE_AI_API_KEY) {
  console.error("GOOGLE_AI_API_KEY not in .env");
  process.exit(1);
}

// yt-dlp location — installed via pip3 to user site-packages
const YTDLP = "/Users/hakielmcqueen/Library/Python/3.9/bin/yt-dlp";

// Check yt-dlp is accessible
const ytdlpCheck = spawnSync(YTDLP, ["--version"], { encoding: "utf8" });
if (ytdlpCheck.error || ytdlpCheck.status !== 0) {
  console.error("yt-dlp not found at", YTDLP);
  process.exit(1);
}
console.log("yt-dlp version:", ytdlpCheck.stdout.trim());

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY);
const fileManager = new GoogleAIFileManager(process.env.GOOGLE_AI_API_KEY);
fs.mkdirSync(AUDIO_TMP, { recursive: true });

// ── Convert session cookies to Netscape format for yt-dlp ────────────────────
function writeCookieFile(cookiePath) {
  if (!fs.existsSync(SESSION_PATH)) return false;
  const session = JSON.parse(fs.readFileSync(SESSION_PATH, "utf8"));
  if (!session.cookies?.length) return false;

  const lines = ["# Netscape HTTP Cookie File", "# Generated by transcribe-lessons.mjs", ""];
  for (const c of session.cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
    const includeSubdomains = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expires && c.expires > 0 ? Math.floor(c.expires) : "0";
    lines.push(`${domain}\t${includeSubdomains}\t${c.path || "/"}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }
  fs.writeFileSync(cookiePath, lines.join("\n"));
  return true;
}

// ── Get the full Vimeo embed URL from a lesson page (includes auth hash) ──────
async function getVimeoEmbedUrl(page, lessonUrl) {
  try {
    await page.goto(lessonUrl, { waitUntil: "domcontentloaded", timeout: 20000 });
    await page.waitForTimeout(2000);
    return await page.evaluate(() => {
      const iframe = document.querySelector('iframe[src*="vimeo.com"]');
      return iframe ? iframe.src : null;
    });
  } catch {
    return null;
  }
}

// ── Download audio with yt-dlp ────────────────────────────────────────────────
function downloadAudio(videoUrl, outputPath) {
  // Download best audio stream in native format (no ffmpeg needed for conversion)
  // Prefer m4a → webm → anything else
  const args = [
    videoUrl,
    "--format", "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio",
    "--output", outputPath + ".%(ext)s",
    "--no-playlist",
    "--no-warnings",
    "--add-header", "Referer:https://adjuster-university.com/",
  ];

  const result = spawnSync(YTDLP, args, { encoding: "utf8", timeout: 180000 });
  if (result.error) throw new Error(`yt-dlp error: ${result.error.message}`);
  if (result.status !== 0) throw new Error(`yt-dlp failed (${result.status}): ${result.stderr || result.stdout}`);

  // Find the file yt-dlp created — only match files with known media extensions
  const AUDIO_EXTS = new Set([".m4a", ".mp4", ".webm", ".mp3", ".wav", ".ogg", ".opus", ".aac"]);
  const dir = path.dirname(outputPath);
  const base = path.basename(outputPath);
  const files = fs.readdirSync(dir).filter(f => {
    const ext = path.extname(f).toLowerCase();
    return f.startsWith(base) && AUDIO_EXTS.has(ext);
  });
  if (files.length > 0) return path.join(dir, files[0]);
  throw new Error("Audio file not found after yt-dlp download");
}

// ── Transcribe audio with Gemini ──────────────────────────────────────────────
async function transcribeWithGemini(audioPath, lessonTitle) {
  if (!fs.existsSync(audioPath)) {
    throw new Error(`Audio file not found: ${audioPath}`);
  }

  const fileSize = fs.statSync(audioPath).size;
  console.log(`     Uploading to Gemini (${(fileSize / 1024 / 1024).toFixed(1)} MB)...`);

  // Detect MIME type from extension
  const ext = path.extname(audioPath).toLowerCase();
  const mimeMap = {
    ".m4a": "audio/mp4",
    ".mp4": "video/mp4",
    ".webm": "audio/webm",
    ".mp3": "audio/mp3",
    ".wav": "audio/wav",
    ".ogg": "audio/ogg",
    ".opus": "audio/opus",
  };
  const mimeType = mimeMap[ext] || "audio/mp4";

  // Upload file to Gemini Files API
  const uploadResult = await fileManager.uploadFile(audioPath, {
    mimeType,
    displayName: lessonTitle,
  });

  const file = uploadResult.file;
  console.log(`     Transcribing (file: ${file.name})...`);

  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
  const result = await model.generateContent([
    {
      fileData: {
        mimeType: file.mimeType,
        fileUri: file.uri,
      },
    },
    `Please provide a complete, accurate transcript of this insurance adjusting training video lesson titled "${lessonTitle}".
    Format the transcript as plain readable text (no timestamps).
    Preserve all spoken content including examples, tips, and explanations.
    If multiple speakers are present, note speaker changes.`,
  ]);

  const transcript = result.response.text();

  // Clean up the uploaded file from Gemini to save quota
  try {
    await fileManager.deleteFile(file.name);
  } catch { /* non-fatal */ }

  return transcript;
}

// ── Patch a markdown file to insert/replace transcript section ────────────────
function patchMarkdownTranscript(mdPath, transcript) {
  if (!fs.existsSync(mdPath)) return false;
  let content = fs.readFileSync(mdPath, "utf8");

  const transcriptSection = `## Video Transcript\n\n${transcript}\n`;
  const placeholder = /\[Transcript not available[^\]]*\]/g;
  const existingSection = /## Video Transcript\n[\s\S]*?(?=\n##|\n$|$)/;

  if (existingSection.test(content)) {
    content = content.replace(existingSection, transcriptSection);
  } else if (placeholder.test(content)) {
    content = content.replace(placeholder, `\n\n${transcriptSection}`);
  } else {
    // Append before Attachments section or at end
    if (content.includes("## Attachments")) {
      content = content.replace("## Attachments", `${transcriptSection}\n## Attachments`);
    } else {
      content += `\n\n${transcriptSection}`;
    }
  }

  fs.writeFileSync(mdPath, content, "utf8");
  return true;
}

// ── Main ──────────────────────────────────────────────────────────────────────
const index = JSON.parse(fs.readFileSync(INDEX_PATH, "utf8"));

// Launch browser to get authenticated embed URLs
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
});
if (fs.existsSync(SESSION_PATH)) {
  const session = JSON.parse(fs.readFileSync(SESSION_PATH, "utf8"));
  if (session.cookies?.length) await context.addCookies(session.cookies);
}
const page = await context.newPage();

let done = 0;
let skipped = 0;
let failed = 0;

for (const course of index.courses) {
  if (FILTER_COURSE && course.slug !== FILTER_COURSE) continue;

  console.log(`\nCourse: ${course.title}`);

  for (const lesson of course.lessons) {
    if (done >= MAX) break;
    if (FILTER_LESSON && lesson.slug !== FILTER_LESSON) continue;
    if (!lesson.hasVideo || lesson.videoProvider !== "vimeo") { skipped++; continue; }

    const mdPath = path.join(OUTPUT_DIR, lesson.file);
    if (!fs.existsSync(mdPath)) { skipped++; continue; }

    // Skip if already transcribed
    const existing = fs.readFileSync(mdPath, "utf8");
    if (existing.includes("## Video Transcript") && !existing.includes("[Transcript not available")) {
      console.log(`  [SKIP] Already transcribed: ${lesson.title}`);
      skipped++;
      continue;
    }

    console.log(`\n  Transcribing: ${lesson.title}`);
    const audioBase = path.join(AUDIO_TMP, `${course.slug}-${lesson.slug}`);

    try {
      // Step 1: Get authenticated Vimeo embed URL from lesson page
      console.log(`     Getting embed URL from lesson page...`);
      const embedUrl = await getVimeoEmbedUrl(page, lesson.url);
      if (!embedUrl) {
        console.log(`     No Vimeo iframe found — skipping`);
        skipped++;
        continue;
      }
      console.log(`     Embed URL: ${embedUrl.slice(0, 80)}...`);

      // Step 2: Download audio with yt-dlp
      console.log(`     Downloading audio...`);
      const audioPath = downloadAudio(embedUrl, audioBase);
      console.log(`     Audio saved: ${audioPath}`);

      // Step 3: Transcribe with Gemini
      const transcript = await transcribeWithGemini(audioPath, lesson.title);
      console.log(`     Transcript: ${transcript.slice(0, 100)}...`);

      // Step 4: Patch markdown file
      patchMarkdownTranscript(mdPath, transcript);
      console.log(`     Saved to ${mdPath}`);

      // Cleanup audio file
      try { fs.unlinkSync(audioPath); } catch { /* ok */ }

      done++;
    } catch (e) {
      console.log(`     FAILED: ${e.message}`);
      failed++;
    }
    if (done + failed >= MAX) break;

    await new Promise(r => setTimeout(r, 1000)); // Brief pause between lessons
  }

  if (done >= MAX) break;
}

await browser.close();

console.log(`\n${"=".repeat(50)}`);
console.log(`TRANSCRIPTION COMPLETE`);
console.log(`Transcribed: ${done} | Skipped: ${skipped} | Failed: ${failed}`);
console.log(`Transcript files updated in: ${OUTPUT_DIR}`);
